# Generated by Django 5.1 on 2024-08-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uploaded_by',
            new_name='author',
        ),
    ]
