# Generated by Django 5.1 on 2024-08-22 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_uploaded_by_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now),
        ),
    ]
