# Generated by Django 5.1 on 2024-08-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_notification_comment_notification_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
    ]
