# Generated by Django 5.1 on 2024-08-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_notification_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='notification_for',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
