# Generated by Django 5.1 on 2024-08-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='banner',
        ),
    ]
